/* Showcase charts - plain DOM, no libraries.
   Data: window.AM_DATA (js/data.js, generated by tools/make_data.py).
   ZINTO is a fictional brand; every figure is synthetic.
   Text is always inserted with textContent, never as HTML. */
(function () {
  'use strict';
  var D = window.AM_DATA;
  if (!D) return;

  var NS = 'http://www.w3.org/2000/svg';
  var tt = document.getElementById('tt');

  /* ---------- helpers ---------- */
  function el(tag, cls, text, attrs) {
    var n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text != null) n.textContent = text;
    if (attrs) Object.keys(attrs).forEach(function (k) { n.setAttribute(k, attrs[k]); });
    return n;
  }
  function pct(v, d) { return (d == null ? 1 : d) === 0 ? Math.round(v) + '%' : v.toFixed(d == null ? 1 : d) + '%'; }
  function signed(v, d) { return (v > 0 ? '+' : v < 0 ? '−' : '') + Math.abs(v).toFixed(d == null ? 1 : d); }
  function legend(a, b) {
    var key = el('div', 'key');
    [['sw-hero', a], ['sw-dim', b]].forEach(function (p) {
      var k = el('span'); k.appendChild(el('i', 'sw ' + p[0])); k.appendChild(document.createTextNode(p[1])); key.appendChild(k);
    });
    return key;
  }
  function ci(o, d) { return o.lo == null ? '' : '95% CI ' + o.lo.toFixed(d == null ? 1 : d) + '–' + o.hi.toFixed(d == null ? 1 : d); }

  /* ---------- tooltip (shared) ---------- */
  function showTip(e, node, v, l, x) {
    if (!tt) return;
    tt.textContent = '';
    tt.appendChild(el('div', 'tt-v', v));
    tt.appendChild(el('div', 'tt-l', l));
    if (x) tt.appendChild(el('div', 'tt-x', x));
    tt.hidden = false;
    var w = tt.offsetWidth, h = tt.offsetHeight, vw = window.innerWidth, vh = window.innerHeight, px, py;
    if (e && e.clientX != null && e.type !== 'focus' && e.type !== 'focusin') {
      px = e.clientX + 14; py = e.clientY + 16;
    } else {
      var r = node.getBoundingClientRect(); px = r.left + Math.min(r.width, 220) / 2; py = r.bottom + 6;
    }
    if (px + w > vw - 8) px = Math.max(8, vw - w - 8);
    if (py + h > vh - 8) py = Math.max(8, py - h - 34);
    tt.style.left = px + 'px'; tt.style.top = py + 'px';
  }
  function hideTip() { if (tt) tt.hidden = true; }
  function bindTip(node, getParts) {
    function go(e) { var p = getParts(); showTip(e, node, p[0], p[1], p[2]); node.classList.add('on'); }
    function stop() { hideTip(); node.classList.remove('on'); }
    node.addEventListener('pointermove', go);
    node.addEventListener('pointerenter', go);
    node.addEventListener('pointerleave', stop);
    node.addEventListener('focus', go);
    node.addEventListener('blur', stop);
  }
  document.addEventListener('keydown', function (e) { if (e.key === 'Escape') hideTip(); });
  window.addEventListener('scroll', hideTip, { passive: true });

  /* ---------- axis ---------- */
  function axis(ticks, fmt, title) {
    var wrap = el('div', 'baxis', null, { 'aria-hidden': 'true' });
    wrap.appendChild(el('span'));
    var inner = el('div', 'baxis-in t' + ticks.length);   // t4 / t5: thinned on narrow screens by the stylesheet
    ticks.forEach(function (t, i) {
      var s = el('span', null, fmt(t));
      s.style.left = (i / (ticks.length - 1) * 100) + '%';
      inner.appendChild(s);
    });
    wrap.appendChild(inner);
    var frag = document.createDocumentFragment();
    frag.appendChild(wrap);
    if (title) { var t = el('div', 'baxis', null, { 'aria-hidden': 'true' }); t.appendChild(el('span')); t.appendChild(el('div', 'axis-title', title)); frag.appendChild(t); }
    return frag;
  }

  /* ---------- bar rows ---------- */
  // o: {max, unit(fmt), colour(item,i), label(item,i) -> bool, tip(item) -> [v,l,x], showCI}
  function barRow(item, i, o) {
    var row = el('div', 'brow' + (item.hero ? ' is-key' : ''), null, { role: 'listitem', tabindex: '0' });
    var tipParts = o.tip(item);
    row.setAttribute('aria-label', tipParts.join('. '));
    row.appendChild(el('div', 'blabel', item.label));
    var track = el('div', 'btrack');
    var w = Math.max(0, Math.min(100, item.value / o.max * 100));
    var bar = el('div', 'bbar');
    bar.style.setProperty('--w', w + '%');
    if (o.colour) { var c = o.colour(item, i); if (c) bar.style.setProperty('--c', c); }
    track.appendChild(bar);
    var hiPct = w;
    if (o.showCI && item.lo != null) {
      var c2 = el('div', 'bci');
      c2.style.setProperty('--lo', (item.lo / o.max * 100) + '%');
      c2.style.setProperty('--hi', (item.hi / o.max * 100) + '%');
      track.appendChild(c2);
      hiPct = item.hi / o.max * 100;
    }
    if (o.label(item, i)) {
      var v = el('span', 'bval', o.unit(item.value));
      v.style.left = 'calc(' + hiPct + '% + 8px)';
      track.appendChild(v);
    }
    row.appendChild(track);
    bindTip(row, function () { return tipParts; });
    return row;
  }

  function bars(items, o, aria) {
    var box = el('div', 'bars', null, { role: 'list', 'aria-label': aria });
    box.style.setProperty('--step', (100 / (o.ticks.length - 1)) + '%');
    var last = null;
    items.forEach(function (it, i) {
      if (it.group && it.group !== last) { box.appendChild(el('div', 'bgroup', it.group, { 'aria-hidden': 'true' })); last = it.group; }
      box.appendChild(barRow(it, i, o));
    });
    box.appendChild(axis(o.ticks, o.tickFmt, o.axisTitle));
    return box;
  }

  /* ---------- table view ---------- */
  function table(caption, head, rows, heroIdx) {
    var t = el('table', 'dtable');
    t.appendChild(el('caption', null, caption));
    var thead = el('thead'), hr = el('tr');
    head.forEach(function (h) { hr.appendChild(el('th', null, h, { scope: 'col' })); });
    thead.appendChild(hr); t.appendChild(thead);
    var tb = el('tbody');
    rows.forEach(function (r, i) {
      var tr = el('tr', heroIdx && heroIdx.indexOf(i) > -1 ? 'is-key' : '');
      r.forEach(function (c, j) { tr.appendChild(el(j === 0 ? 'th' : 'td', null, String(c), j === 0 ? { scope: 'row' } : null)); });
      tb.appendChild(tr);
    });
    t.appendChild(tb);
    return t;
  }

  /* chart / table switch: both views stay in the DOM, one is hidden */
  function wireSwitch(card) {
    var btns = card.querySelectorAll('.seg button'), cv = card.querySelector('[data-view="chart"]'), tv = card.querySelector('[data-view="table"]');
    if (!btns.length || !cv || !tv) return;
    Array.prototype.forEach.call(btns, function (b) {
      b.addEventListener('click', function () {
        var showTable = b.getAttribute('data-show') === 'table';
        cv.hidden = showTable; tv.hidden = !showTable;
        Array.prototype.forEach.call(btns, function (x) { x.setAttribute('aria-pressed', String(x === b)); });
        hideTip();
      });
    });
  }

  /* ---------- 1. aided awareness, all brands ---------- */
  function awareness() {
    var host = document.getElementById('c-awareness'); if (!host) return;
    var items = D.awareness.map(function (a, i) { return { label: a.label, value: a.value, lo: a.lo, hi: a.hi, n: a.n, hero: a.hero, rank: i + 1 }; });
    host.appendChild(legend(D.hero, 'Other brands'));
    host.appendChild(bars(items, {
      max: 100, ticks: [0, 25, 50, 75, 100], tickFmt: function (t) { return t + '%'; },
      axisTitle: 'Share of respondents who recognise the brand (aided awareness)',
      unit: function (v) { return pct(v); }, showCI: true,
      label: function (it, i) { return it.hero || i === 0; },
      tip: function (it) { return [pct(it.value), it.label + ', rank ' + it.rank + ' of ' + items.length, ci(it) + ' · ' + it.n + ' respondents aware']; }
    }, 'Aided awareness by brand'));
    return items;
  }

  /* ---------- 2. funnel ---------- */
  function funnel(host, compact) {
    if (!host) return;
    var F = D.funnel, ramp = ['var(--ramp-1)', 'var(--ramp-3)', 'var(--ramp-5)'];
    var box = el('div', 'funnel', null, { role: 'list', 'aria-label': D.hero + ' funnel' });
    var max = 50;
    F.stages.forEach(function (s, i) {
      var st = el('div', 'fstage', null, { role: 'listitem', tabindex: '0' });
      st.setAttribute('aria-label', s.label + ': ' + pct(s.value) + ' of all respondents, ' + s.n + ' people');
      var top = el('div', 'fstage-top'); top.appendChild(el('span', null, s.label)); top.appendChild(el('b', null, pct(s.value)));
      st.appendChild(top);
      var tr = el('div', 'ftrack'); var b = el('div', 'fbar');
      b.style.setProperty('--w', (s.value / max * 100) + '%'); b.style.setProperty('--c', ramp[i]);
      tr.appendChild(b); st.appendChild(tr);
      bindTip(st, function () { return [pct(s.value), s.label, s.n + ' of ' + D.field.at.net + ' respondents (weighted share shown)']; });
      box.appendChild(st);
      if (!compact && i < F.conv.length) {
        var c = F.conv[i], cv = el('div', 'fconv');
        var bnode = el('b', null, pct(c.value, 0));
        cv.appendChild(bnode);
        cv.appendChild(el('span', null, i === 0 ? 'of those aware would consider it' : 'of those considering it also bought'));
        cv.appendChild(el('span', 'chip', 'category median ' + pct(c.median, 0)));
        box.appendChild(cv);
      }
    });
    host.appendChild(box);
  }

  /* ---------- 3. who knows the brand ---------- */
  function who() {
    var host = document.getElementById('c-who'); if (!host) return;
    var ramp = ['var(--ramp-1)', 'var(--ramp-2)', 'var(--ramp-3)', 'var(--ramp-4)', 'var(--ramp-5)'];
    var items = [];
    D.age.forEach(function (a) { items.push({ group: 'Age', label: a.label, value: a.value, lo: a.lo, hi: a.hi, n: a.n, ramp: true }); });
    D.gender.forEach(function (a) { items.push({ group: 'Gender', label: a.label, value: a.value, lo: a.lo, hi: a.hi, n: a.n }); });
    D.education.forEach(function (a) { items.push({ group: 'Education', label: a.label, value: a.value, lo: a.lo, hi: a.hi, n: a.n }); });
    var ai = 0;
    host.appendChild(bars(items, {
      max: 80, ticks: [0, 20, 40, 60, 80], tickFmt: function (t) { return t + '%'; },
      axisTitle: 'Share who recognise ' + D.hero + ' (aided awareness)',
      unit: function (v) { return pct(v); }, showCI: true,
      colour: function (it) { return it.ramp ? ramp[ai++ % 5] : 'var(--mark)'; },
      label: function () { return true; },
      tip: function (it) { return [pct(it.value), it.group + ': ' + it.label, ci(it) + ' · ' + it.n + ' respondents']; }
    }, 'Aided awareness by age, gender and education'));
    return items;
  }

  /* ---------- 4. contact channels ---------- */
  function channels() {
    var host = document.getElementById('c-channels'); if (!host) return;
    var items = D.channels;
    host.appendChild(bars(items, {
      max: 60, ticks: [0, 20, 40, 60],
      tickFmt: function (t) { return t + '%'; },
      axisTitle: 'Share of aware respondents who noticed the brand there (multiple answers)',
      unit: function (v) { return pct(v); }, showCI: true,
      colour: function () { return 'var(--mark)'; },
      label: function () { return true; },
      tip: function (it) { return [pct(it.value), it.label, ci(it) + ' · ' + it.n + ' of ' + D.field.at.aware + ' aware respondents']; }
    }, 'Where aware respondents noticed the brand'));
    return items;
  }

  /* ---------- 5. change across waves (diverging around zero) ---------- */
  function change() {
    var host = document.getElementById('c-change'); if (!host) return;
    var items = D.change.map(function (c) { return { label: c.label, value: c.value, lo: c.lo, hi: c.hi, hero: c.hero, w2022: c.w2022, w2026: c.w2026 }; });
    host.appendChild(legend(D.hero, 'Comparison brands'));
    var M = 20, box = el('div', 'bars', null, { role: 'list', 'aria-label': 'Change in aided awareness 2022 to 2026' });
    box.style.setProperty('--step', '25%');
    items.forEach(function (it) {
      var row = el('div', 'brow' + (it.hero ? ' is-key' : ''), null, { role: 'listitem', tabindex: '0' });
      var parts = [signed(it.value) + ' pp', it.label + ': ' + pct(it.w2022) + ' in 2022, ' + pct(it.w2026) + ' in 2026', ci(it) + ' pp'];
      row.setAttribute('aria-label', parts.join('. '));
      row.appendChild(el('div', 'blabel', it.label));
      var tr = el('div', 'btrack'); tr.appendChild(el('div', 'bzero'));
      var neg = it.value < 0, wv = Math.abs(it.value) / (2 * M) * 100;
      var b = el('div', 'bbar' + (neg ? ' neg' : ''));
      b.style.setProperty('--w', wv + '%'); b.style.left = neg ? (50 - wv) + '%' : '50%';
      tr.appendChild(b);
      if (it.hero) {
        var c = el('div', 'bci');
        c.style.setProperty('--lo', (50 + it.lo / (2 * M) * 100) + '%'); c.style.setProperty('--hi', (50 + it.hi / (2 * M) * 100) + '%');
        tr.appendChild(c);
        var v = el('span', 'bval', signed(it.value) + ' pp'); v.style.left = 'calc(' + (50 + it.hi / (2 * M) * 100) + '% + 8px)'; tr.appendChild(v);
      }
      row.appendChild(tr); bindTip(row, function () { return parts; });
      box.appendChild(row);
    });
    box.appendChild(axis([-20, -10, 0, 10, 20], function (t) { return (t > 0 ? '+' : t < 0 ? '−' : '') + Math.abs(t); }, 'Change in aided awareness, percentage points (2026 minus 2022)'));
    host.appendChild(box);
    return items;
  }

  /* ---------- build + table views ---------- */
  function addTable(id, caption, head, rows, heroIdx) {
    var host = document.getElementById(id); if (!host) return;
    host.appendChild(table(caption, head, rows, heroIdx));
  }
  function ciCell(o, d) { return o.lo == null ? '' : o.lo.toFixed(d == null ? 1 : d) + '–' + o.hi.toFixed(d == null ? 1 : d); }

  var aw = awareness();
  addTable('t-awareness', 'Aided awareness by brand, Austria (synthetic data)', ['Brand', 'Aware, %', '95% CI', 'Aware (n)'],
    aw.map(function (a) { return [a.label, a.value.toFixed(1), ciCell(a), a.n]; }), [aw.findIndex(function (a) { return a.hero; })]);

  funnel(document.getElementById('c-funnel'), false);
  funnel(document.getElementById('hero-funnel'), true);
  addTable('t-funnel', 'Funnel for ' + D.hero + ', Austria (synthetic data)', ['Stage', 'Share of all, %', 'People (n)'],
    D.funnel.stages.map(function (s) { return [s.label, s.value.toFixed(1), s.n]; })
      .concat(D.funnel.conv.map(function (c) { return [c.label + ' (' + D.hero + ' / category median of ' + c.brands + ' brands)', c.value.toFixed(1) + ' / ' + c.median.toFixed(1), '']; })));

  var wi = who();
  addTable('t-who', 'Aided awareness of ' + D.hero + ' by group, Austria (synthetic data)', ['Group', 'Aware, %', '95% CI', 'Respondents (n)'],
    wi.map(function (a) { return [a.group + ': ' + a.label, a.value.toFixed(1), ciCell(a), a.n]; }));

  var chs = channels();
  addTable('t-channels', 'Where aware respondents noticed ' + D.hero + ', Austria (synthetic data)', ['Channel', 'Share, %', '95% CI', 'Respondents (n)'],
    chs.map(function (a) { return [a.label, a.value.toFixed(1), ciCell(a), a.n]; }));

  var ch = change();
  addTable('t-change', 'Aided awareness 2022 and 2026, Austria (synthetic data)', ['Brand', '2022, %', '2026, %', 'Change, pp', '95% CI, pp'],
    ch.map(function (a) { return [a.label, a.w2022.toFixed(1), a.w2026.toFixed(1), signed(a.value), ciCell(a)]; }), [ch.findIndex(function (a) { return a.hero; })]);

  Array.prototype.forEach.call(document.querySelectorAll('.chart'), wireSwitch);

  /* ---------- fill every figure in the text from the data ---------- */
  var fa = D.field.at, fd = D.field.de, T = D.tracking, hero = D.change.filter(function (c) { return c.hero; })[0];
  var next = D.awareness[D.rank];            // best-known brand below the hero
  var vals = {
    net: fa.net.toLocaleString('en-GB'), minutes: fa.minutes.toFixed(1) + ' min', excl: pct(fa.excluded_pct),
    deff: fa.deff.toFixed(2), brands: String(D.brands), aware: String(fa.aware),
    de_net: fd.net.toLocaleString('en-GB'), de_aware: String(fd.aware), de_consider: String(fd.consider), de_buy: String(fd.buy),
    aware_pct: pct(D.awareness[D.rank - 1].value), rank: D.rank + ' of ' + D.brands,
    ratio: (D.awareness[D.rank - 1].value / next.value).toFixed(1) + '×', nextname: next.label, nextpct: pct(next.value),
    conv1: pct(D.funnel.conv[0].value, 0), med1: pct(D.funnel.conv[0].median, 0),
    conv2: pct(D.funnel.conv[1].value, 0), med2: pct(D.funnel.conv[1].median, 0),
    store: pct(D.channels[0].value, 0),
    age_young: pct(D.age[0].value, 0), age_old: pct(D.age[D.age.length - 1].value, 0),
    women: pct(D.gender[1].value, 0), men: pct(D.gender[0].value, 0),
    raw: signed(hero.value) + ' pp', ctrl_median: signed(T.control_median) + ' pp', adj: signed(T.adjusted) + ' pp',
    adj_ci: '95% interval ' + signed(T.ci_lo) + ' to ' + signed(T.ci_hi) + ' pp', exp: pct(T.expected) + ' expected',
    ncontrol: String(D.change.length - 1), n22: T.n_2022.toLocaleString('en-GB'), n26: T.n_2026.toLocaleString('en-GB')
  };
  Array.prototype.forEach.call(document.querySelectorAll('[data-bind]'), function (n) {
    var k = n.getAttribute('data-bind');
    if (k in vals) n.textContent = vals[k];
  });
})();
