/* Generated by tools/make_data.py - do not edit by hand.
   ZINTO is a fictional brand; every figure is synthetic. */
window.AM_DATA = {
 "note": "ZINTO is a fictional brand. All figures are synthetic.",
 "hero": "ZINTO",
 "rank": 13,
 "brands": 20,
 "awareness": [
  {
   "label": "Orbix",
   "value": 96.6,
   "lo": 94.8,
   "hi": 97.8,
   "n": 576,
   "hero": false
  },
  {
   "label": "Lunara",
   "value": 95.0,
   "lo": 92.9,
   "hi": 96.5,
   "n": 568,
   "hero": false
  },
  {
   "label": "Cocoway",
   "value": 92.3,
   "lo": 89.8,
   "hi": 94.2,
   "n": 551,
   "hero": false
  },
  {
   "label": "Crunchor",
   "value": 91.8,
   "lo": 89.3,
   "hi": 93.8,
   "n": 548,
   "hero": false
  },
  {
   "label": "Vollmond",
   "value": 89.6,
   "lo": 86.9,
   "hi": 91.9,
   "n": 536,
   "hero": false
  },
  {
   "label": "Almgold",
   "value": 89.0,
   "lo": 86.2,
   "hi": 91.3,
   "n": 533,
   "hero": false
  },
  {
   "label": "Knusperli",
   "value": 88.4,
   "lo": 85.5,
   "hi": 90.7,
   "n": 528,
   "hero": false
  },
  {
   "label": "Balmo",
   "value": 85.6,
   "lo": 82.6,
   "hi": 88.2,
   "n": 511,
   "hero": false
  },
  {
   "label": "Alpzart",
   "value": 79.2,
   "lo": 75.7,
   "hi": 82.3,
   "n": 473,
   "hero": false
  },
  {
   "label": "Hazelo",
   "value": 74.3,
   "lo": 70.6,
   "hi": 77.7,
   "n": 443,
   "hero": false
  },
  {
   "label": "Granova",
   "value": 72.5,
   "lo": 68.7,
   "hi": 76.0,
   "n": 435,
   "hero": false
  },
  {
   "label": "Snapup",
   "value": 70.2,
   "lo": 66.4,
   "hi": 73.8,
   "n": 418,
   "hero": false
  },
  {
   "label": "ZINTO",
   "value": 46.3,
   "lo": 42.3,
   "hi": 50.4,
   "n": 267,
   "hero": true
  },
  {
   "label": "Nutriq",
   "value": 30.5,
   "lo": 26.9,
   "hi": 34.4,
   "n": 175,
   "hero": false
  },
  {
   "label": "Protera",
   "value": 15.3,
   "lo": 12.6,
   "hi": 18.4,
   "n": 88,
   "hero": false
  },
  {
   "label": "Sportlab",
   "value": 13.9,
   "lo": 11.3,
   "hi": 17.0,
   "n": 80,
   "hero": false
  },
  {
   "label": "Nordfit",
   "value": 11.5,
   "lo": 9.1,
   "hi": 14.3,
   "n": 67,
   "hero": false
  },
  {
   "label": "Nutrika",
   "value": 10.8,
   "lo": 8.5,
   "hi": 13.5,
   "n": 64,
   "hero": false
  },
  {
   "label": "Cacaolu",
   "value": 4.9,
   "lo": 3.4,
   "hi": 7.0,
   "n": 28,
   "hero": false
  },
  {
   "label": "Ketolino",
   "value": 3.2,
   "lo": 2.1,
   "hi": 5.0,
   "n": 20,
   "hero": false
  }
 ],
 "funnel": {
  "stages": [
   {
    "label": "Aware of the brand",
    "value": 46.3,
    "n": 267
   },
   {
    "label": "Would consider at next purchase",
    "value": 15.0,
    "n": 84
   },
   {
    "label": "Bought in the last 3 months",
    "value": 9.8,
    "n": 55
   }
  ],
  "conv": [
   {
    "label": "Aware to consider",
    "value": 32.4,
    "median": 41.4,
    "brands": 18
   },
   {
    "label": "Consider to buy",
    "value": 56.4,
    "median": 56.2,
    "brands": 14
   }
  ]
 },
 "age": [
  {
   "label": "18–29",
   "value": 66.18,
   "lo": 57.25,
   "hi": 74.09,
   "n": 120
  },
  {
   "label": "30–39",
   "value": 51.14,
   "lo": 42.13,
   "hi": 60.07,
   "n": 116
  },
  {
   "label": "40–49",
   "value": 42.57,
   "lo": 34.38,
   "hi": 51.2,
   "n": 129
  },
  {
   "label": "50–59",
   "value": 37.47,
   "lo": 29.34,
   "hi": 46.38,
   "n": 122
  },
  {
   "label": "60+",
   "value": 26.14,
   "lo": 18.86,
   "hi": 35.01,
   "n": 111
  }
 ],
 "gender": [
  {
   "label": "Men",
   "value": 39.99,
   "lo": 34.66,
   "hi": 45.57,
   "n": 309
  },
  {
   "label": "Women",
   "value": 52.61,
   "lo": 46.77,
   "hi": 58.38,
   "n": 289
  }
 ],
 "education": [
  {
   "label": "Compulsory school / apprenticeship",
   "value": 44.81,
   "lo": 38.32,
   "hi": 51.48,
   "n": 220
  },
  {
   "label": "A-levels (Matura)",
   "value": 47.96,
   "lo": 40.35,
   "hi": 55.67,
   "n": 163
  },
  {
   "label": "University degree",
   "value": 46.15,
   "lo": 39.08,
   "hi": 53.37,
   "n": 187
  }
 ],
 "channels": [
  {
   "label": "In store (shelf, display)",
   "value": 52.8,
   "lo": 46.8,
   "hi": 58.8,
   "n": 141
  },
  {
   "label": "Instagram / Facebook",
   "value": 29.9,
   "lo": 24.7,
   "hi": 35.7,
   "n": 77
  },
  {
   "label": "Word of mouth",
   "value": 17.4,
   "lo": 13.2,
   "hi": 22.4,
   "n": 47
  },
  {
   "label": "TV advertising",
   "value": 15.5,
   "lo": 11.6,
   "hi": 20.4,
   "n": 42
  },
  {
   "label": "YouTube",
   "value": 14.2,
   "lo": 10.5,
   "hi": 19.0,
   "n": 37
  },
  {
   "label": "TikTok",
   "value": 12.4,
   "lo": 8.9,
   "hi": 16.9,
   "n": 32
  },
  {
   "label": "Print advertising",
   "value": 11.0,
   "lo": 7.8,
   "hi": 15.4,
   "n": 30
  }
 ],
 "change": [
  {
   "label": "ZINTO",
   "value": 13.8,
   "lo": 8.5,
   "hi": 19.0,
   "w2022": 32.5,
   "w2026": 46.3,
   "hero": true
  },
  {
   "label": "Ketolino",
   "value": -0.0,
   "lo": -2.0,
   "hi": 2.0,
   "w2022": 3.3,
   "w2026": 3.2,
   "hero": false
  },
  {
   "label": "Orbix",
   "value": -1.0,
   "lo": -3.0,
   "hi": 0.8,
   "w2022": 97.6,
   "w2026": 96.6,
   "hero": false
  },
  {
   "label": "Lunara",
   "value": -1.4,
   "lo": -3.8,
   "hi": 0.8,
   "w2022": 96.4,
   "w2026": 95.0,
   "hero": false
  },
  {
   "label": "Cocoway",
   "value": -3.0,
   "lo": -5.7,
   "hi": -0.4,
   "w2022": 95.2,
   "w2026": 92.3,
   "hero": false
  },
  {
   "label": "Crunchor",
   "value": -3.9,
   "lo": -6.7,
   "hi": -1.3,
   "w2022": 95.7,
   "w2026": 91.8,
   "hero": false
  },
  {
   "label": "Vollmond",
   "value": -4.0,
   "lo": -7.2,
   "hi": -1.1,
   "w2022": 93.7,
   "w2026": 89.6,
   "hero": false
  },
  {
   "label": "Knusperli",
   "value": -4.1,
   "lo": -7.4,
   "hi": -0.9,
   "w2022": 92.4,
   "w2026": 88.4,
   "hero": false
  },
  {
   "label": "Nutrika",
   "value": -4.7,
   "lo": -8.3,
   "hi": -1.0,
   "w2022": 15.5,
   "w2026": 10.8,
   "hero": false
  },
  {
   "label": "Cacaolu",
   "value": -5.1,
   "lo": -7.9,
   "hi": -2.2,
   "w2022": 10.0,
   "w2026": 4.9,
   "hero": false
  },
  {
   "label": "Almgold",
   "value": -6.2,
   "lo": -9.3,
   "hi": -3.3,
   "w2022": 95.2,
   "w2026": 89.0,
   "hero": false
  },
  {
   "label": "Nordfit",
   "value": -7.1,
   "lo": -10.9,
   "hi": -3.2,
   "w2022": 18.6,
   "w2026": 11.5,
   "hero": false
  },
  {
   "label": "Balmo",
   "value": -7.6,
   "lo": -11.1,
   "hi": -4.3,
   "w2022": 93.3,
   "w2026": 85.6,
   "hero": false
  },
  {
   "label": "Alpzart",
   "value": -8.1,
   "lo": -12.2,
   "hi": -4.1,
   "w2022": 87.3,
   "w2026": 79.2,
   "hero": false
  },
  {
   "label": "Sportlab",
   "value": -8.7,
   "lo": -12.7,
   "hi": -4.5,
   "w2022": 22.6,
   "w2026": 13.9,
   "hero": false
  },
  {
   "label": "Granova",
   "value": -9.5,
   "lo": -14.1,
   "hi": -5.0,
   "w2022": 82.0,
   "w2026": 72.5,
   "hero": false
  },
  {
   "label": "Hazelo",
   "value": -10.7,
   "lo": -15.1,
   "hi": -6.3,
   "w2022": 85.0,
   "w2026": 74.3,
   "hero": false
  },
  {
   "label": "Snapup",
   "value": -14.2,
   "lo": -18.7,
   "hi": -9.7,
   "w2022": 84.4,
   "w2026": 70.2,
   "hero": false
  }
 ],
 "tracking": {
  "control_median": -5.1,
  "expected": 22.4,
  "measured": 46.3,
  "adjusted": 23.9,
  "ci_lo": 18.5,
  "ci_hi": 29.0,
  "n_2022": 795,
  "n_2026": 598
 },
 "field": {
  "at": {
   "interviews": 648,
   "net": 598,
   "excluded_pct": 7.7,
   "minutes": 2.5,
   "deff": 1.021,
   "n_eff": 585,
   "aware": 267
  },
  "de": {
   "interviews": 1240,
   "net": 1018,
   "excluded_pct": 17.9,
   "minutes": 2.2,
   "deff": 1.025,
   "n_eff": 994,
   "aware": 62,
   "consider": 12,
   "buy": 9
  }
 }
};
