#!/usr/bin/env python3
"""Turn the dashboard generated by the ZINTO case-study pipeline into
showcase/dashboard.html.

ZINTO is a fictional brand and the data are synthetic. The generated file is a
bare fragment, so this script

  * wraps it in a proper document (doctype, charset, viewport, noindex),
  * removes the Google Fonts request, so the page makes no third-party call
    (the font stack falls back to Helvetica Neue / Arial),
  * puts a banner on top that says what the page is and links back, and wraps the
    page in header and main landmarks,
  * lifts three colours that failed the 4.5:1 text-contrast minimum,
  * replaces two lines that referred to an internal report and to an author.

Usage:
    python3 tools/make_demo_dashboard.py <folder with the pipeline output>
"""
import io, os, re, sys

if len(sys.argv) != 2:
    sys.exit(__doc__)
SRC = os.path.join(sys.argv[1], 'DASHBOARD.html')
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   'showcase', 'dashboard.html')

s = io.open(SRC, encoding='utf-8').read()


def swap(old, new, count=1):
    global s
    assert s.count(old) == count, 'expected %d x %r, found %d' % (count, old[:60], s.count(old))
    s = s.replace(old, new)


# 1. no third-party font request
s, n = re.subn(r'<link rel="stylesheet" href="https://fonts\.googleapis\.com[^>]*>\s*', '', s)
assert n == 1, 'font link not found'

# 2. contrast: the generated muted grey is 2.7:1 on the page, below the 4.5:1 minimum for
#    small text. The reset link (brand red) is 3.8:1 on light and 4.4:1 on dark.
swap('--muted:#9e9997;', '--muted:#68635f;')

# 2b. neutral wording
swap('<title>ZINTO Markenmonitor</title>', '')
# the closing clause of the table hint cites an internal field report; the footer names an author
s, n = re.subn(r'Regionalaussagen ist die Stichprobe zu klein, und die deutsche Bundeslandangabe ist\s+defekt \([^)]*\)\.',
               'Regionalaussagen ist die Stichprobe zu klein.', s)
assert n == 1, 'table hint not found'
s, n = re.subn(r'<span>[^<]*Markenstudie ZINTO September 2026</span>',
               '<span>alpha-metrics.ai \u00b7 Demo mit synthetischen Daten (fiktive Marke ZINTO)</span>', s)
assert n == 1, 'footer not found'

# 3. split head (style) from body, then wrap
head, sep, body = s.partition('</style>')
assert sep, 'no </style> found'
assert '<script' not in head

banner_css = """
#reset{color:#c2351f}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]) #reset{color:#f0583f}}
:root[data-theme="dark"] #reset{color:#f0583f}
.am-banner{display:flex;flex-wrap:wrap;gap:6px 18px;justify-content:space-between;align-items:center;
  background:#0e1a2b;color:#fff;font:500 .86rem/1.45 system-ui,-apple-system,"Segoe UI",Roboto,Arial,sans-serif;padding:10px 18px}
.am-banner a{color:#9ec5f4;font-weight:700}
.am-banner a:focus-visible{outline:3px solid #9ec5f4;outline-offset:3px}
"""
banner = ('<header class="am-banner" lang="en"><span><strong>Demo dashboard.</strong> Fictional brand ZINTO, '
          'synthetic data, German interface.</span>'
          '<a href="../index.html#showcase">Back to alpha-metrics.ai</a></header>\n')

doc = ('<!DOCTYPE html>\n<html lang="de">\n<head>\n<meta charset="utf-8">\n'
       '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
       '<meta name="robots" content="noindex,follow">\n'
       '<title>Demo-Dashboard | alpha-metrics.ai (synthetische Daten)</title>\n'
       + head.strip() + banner_css + '</style>\n</head>\n<body>\n' + banner + '<main>\n' + body.strip() + '\n</main>\n</body>\n</html>\n')

# 4. nothing external may remain
ext = re.findall(r'(?:src|href)=["\']https?://[^"\']+', doc) + re.findall(r'url\(["\']?https?://', doc)
assert not ext, 'external references remain: %r' % ext[:3]

os.makedirs(os.path.dirname(OUT), exist_ok=True)
io.open(OUT, 'w', encoding='utf-8').write(doc)
print('wrote %s (%d bytes)' % (OUT, len(doc.encode('utf-8'))))
